### PR TITLE
Completed Vietnamese translations

### PR DESCRIPTION
**Pull request by pdawarrior**
I have completed Vietnamese translations!

### CODE REVIEW

**Comment by thomasmars** [comment]
Thanks, you should not delete .en.json though, it is required for the translations.

**Comment by pdawarrior** [comment]
Sorry, I am not aware of that.

**Comment by thomasmars** [comment]
Great work. Thanks! :1st_place_medal:

**Comment by pdawarrior** [comment]
Thank you very much for your prompt response. I will try my best with the rest.

**Pull request merged**
